BEGIN TRANSACTION;
CREATE TABLE "scheduler"(
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	date CHAR(8) NOT NULL DEFAULT "",
	title VARCHAR(128) NOT NULL DEFAULT "",
	comment TEXT DEFAULT "",
	repeat VARCHAR(128)	
);
CREATE INDEX idx_scheduler_date ON scheduler(date);
COMMIT;